<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Administration' => 'Upravjanje',
    'Event types' => 'Vrste dogodkov',
    'Local codes' => 'Lokalni šifranti',
    'Lock types' => 'Vrste ključavnic',
    'Management types' => 'Tipi upravljanja zgradb, prostorov in sredstev',
    'Membership types' => 'Vrste članstva v organizacijah',
    'Organization types' => 'Vrste organizacij',
    'Participation types' => 'Načini udeležbe na dogodkih',
    'Partnership types' => 'Vrste partnerstev v projektih',
    'Product types' => 'Vrste produktov',
    'Project types' => 'Vrste projektov',
    'Role types' => 'Vrste vlog v projektih',
    'Room types' => 'Vrste prostorov',
    'Statuses' => 'Statusi',
    'About' => 'O programu',
    'Access control system.' => 'Sistem za upravljanje - malo drugače ;)',
    'Activity Type ID' => 'Šifra dejavnosti',
    'Activity type codes' => 'Klasifikacija dejavnosti',
    'Are you sure you want to delete this item?' => 'Gotovo želiš izbrisati ta zapis?',
    'Birth Date' => 'Datum rojstva',
    'Country Code' => 'Oznaka države',
    'Country codes' => 'Oznake držav',
    'Create' => 'Dodaj',
    'Create Organization' => 'Dodaj organizacijo',
    'Create Person' => 'Ustvari osebo',
    'Created At' => 'Ustvarjeno',
    'Created By' => 'Ustvaril',
    'Created by' => 'Ustvaril',
    'Delete' => 'Izbriši',
    'Description' => 'Opis',
    'Domain' => 'Domena',
    'Email' => 'Elektronski naslov',
    'First Name' => 'Ime',
    'Full Name' => 'Polno ime',
    'Gateway' => 'Dostop',
    'Global codes' => 'Globalni šifranti',
    'Home' => 'Domov',
    'House No' => 'Hišna številka',
    'ID' => 'ID',
    'Language' => 'Jezik',
    'Last Name' => 'Priimek',
    'Logout' => 'Odjava',
    'Municipality ID' => 'Občina',
    'Municipality IDs' => 'Šifre občin',
    'Name' => 'Ime',
    'Organization Type ID' => 'Šifra vrste organizacije',
    'Organizations' => 'Organizacije',
    'People' => 'Osebe',
    'Person ID' => 'Šifra',
    'Phone' => 'Telefon',
    'Postal Code' => 'Poštna številka',
    'Postal codes' => 'Poštne številke',
    'Promoted' => 'Predstavljen',
    'Registration Number' => 'Matična številka',
    'Reset' => 'Ponastavi',
    'Search' => 'Iskanje',
    'Sex' => 'Spol',
    'Sign In' => 'Prijava',
    'Slug' => 'Žeton',
    'Status ID' => 'Status',
    'Street ID' => 'Ulica',
    'Street IDs' => 'Šifre ulic',
    'Tax ID' => 'Davčna številka',
    'Tax IDs' => 'Davčne številke',
    'Update' => 'Posodobi',
    'Update {modelClass}: ' => 'Posodobi {modelClass}: ',
    'Updated At' => 'Spremenjeno',
    'Updated By' => 'Spremenil',
    'Updated by' => 'Spremenil',
    'User ID' => 'Uporabnik',
    'Users' => 'Uporabniki',
    'Webpage' => 'Spletna stran',
];
