<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => '',
    'Access control system.' => '',
    'Activity Type ID' => '',
    'Activity type codes' => '',
    'Administration' => '',
    'Are you sure you want to delete this item?' => '',
    'Birth Date' => '',
    'Code' => '',
    'Country Code' => '',
    'Country codes' => '',
    'Create' => '',
    'Create Organization' => '',
    'Create Person' => '',
    'Created At' => '',
    'Created By' => '',
    'Created by' => '',
    'Data' => '',
    'Delete' => '',
    'Description' => '',
    'Domain' => '',
    'Email' => '',
    'Event types' => '',
    'First Name' => '',
    'Full Name' => '',
    'Gateway' => '',
    'General' => '',
    'Global codes' => '',
    'Home' => '',
    'House No' => '',
    'ID' => '',
    'Language' => '',
    'Last Name' => '',
    'Local codes' => '',
    'Location' => '',
    'Lock types' => '',
    'Logout' => '',
    'Management types' => '',
    'Membership types' => '',
    'Municipality ID' => '',
    'Municipality IDs' => '',
    'Name' => '',
    'Organization ID' => '',
    'Organization Type ID' => '',
    'Organization types' => '',
    'Organizations' => '',
    'Participation types' => '',
    'Partnership types' => '',
    'People' => '',
    'Person ID' => '',
    'Phone' => '',
    'Postal Code' => '',
    'Postal codes' => '',
    'Product types' => '',
    'Project types' => '',
    'Promoted' => '',
    'Registration Number' => '',
    'Reset' => '',
    'Role types' => '',
    'Room types' => '',
    'Search' => '',
    'Sex' => '',
    'Sign In' => '',
    'Slug' => '',
    'Status ID' => '',
    'Statuses' => '',
    'Street ID' => '',
    'Street IDs' => '',
    'Tax ID' => '',
    'Tax IDs' => '',
    'Update' => '',
    'Update {modelClass}: ' => '',
    'Updated At' => '',
    'Updated By' => '',
    'Updated by' => '',
    'User ID' => '',
    'Users' => '',
    'Webpage' => '',
];
